[package]
name = "bpf-full-cone-nat"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0"
authors = ["Huang-Huang Bao <i@eh5.me>"]
rust-version = "1.74"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[features]
default = []
ipv6 = []
# Required on 32-bit platforms
bindgin = ["libbpf-sys/bindgen"]
# Link against static `libelf` and `zlib`.
static = ["libbpf-sys/static"]
#
# libbpf is vendrored and static in any case.
#

[dependencies]
anyhow = "1.0.80"
async-stream = "0.3.5"
bitflags = { version = "2.4.2", features = ["bytemuck"] }
bytemuck = { version = "1.14.0", features = ["derive"] }
fundu = "2.0.0"
futures-util = { version = "0.3.30", default-features = false, features = [
    "std",
] }
ipnet = { version = "2.9.0", features = ["serde"] }
lexopt = "0.3.0"
libbpf-rs = "0.22.0"
libbpf-sys = "1.2.1"
libc = "0.2.151"
netlink-packet-core = "0.7.0"
netlink-packet-route = "0.19.0"
netlink-sys = "0.8.5"
nix = "0.27.1"
prefix-trie = "0.2.5"
rtnetlink = "0.14.1"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.35.1", features = ["macros", "rt", "signal", "sync"] }
toml = { version = "0.8.10", default-features = false, features = ["parse"] }

[build-dependencies]
libbpf-cargo = "0.22.0"
